### ISSUE TITLE
为什么类的成员要有不同的访问级别

### ISSUE THREAD

**Issue by jihuayu** [jihuayu/FZU-OOP-2020#14]
## 问题
（1.25）为什么类的成员要有不同的访问级别

## 问题概述
既然类的成员可以通过指针偏移的方式被修改，引用，那么私有成员有什么意义？

## 其他
此为思考题，请熟练人员给其他同学留下机会。

**Comment by xiao-qingjiang** [comment]
字段、方法、属性都可以叫做类的成员Member，它们都需要定义访问级别。访问级别的用处在于控制成员在哪些地方可以被访问，这样可以·达到面向对象中“封装”的目的。
几个访问级别：public（任何地方都可以访问）；private（默认级别。只能由本类中的成员访问）。还有internal、protected两个级别。

**Comment by jihuayu** [comment]
那我可以把所有成员开成public吗？
这样大家就可以随便调用，不是很方便吗？

**Comment by fzuycy** [comment]
> 那我可以把所有成员开成public吗？
> 这样大家就可以随便调用，不是很方便吗？

如果全都设为public，这样所有的数据都能被别人访问，从而某些数据的安全性和合法性就没法被保证，通俗点说，就是你不知道别人会对某些类的属性做什么，或者拿来干嘛，然后别人要是改了数据，对于那些比较大的项目来说，你也很难检查出哪些数据被别人做了改动

**Comment by xiao-qingjiang** [comment]
不能，当字段为 public 时，其他对象可以直接访问该字段并对其进行修改，而不会被拥有该字段的对象检测到。

**Comment by xiao-qingjiang** [comment]
> 那我可以把所有成员开成public吗？
> 这样大家就可以随便调用，不是很方便吗？
当字段为 public 时，其他对象可以直接访问该字段并对其进行修改，而不会被拥有该字段的对象检测到。

**Comment by jihuayu** [comment]
那我可以不可以把所有的成员变量开成private，然后通过类的函数，取入取出。

**Comment by chinese-Qtea** [comment]
如果外部程序不是经常需要使用这个类成员变量的话, 对程序的效率影响不大,

**Comment by chinese-Qtea** [comment]
> 那我可以不可以把所有的成员变量开成private，然后通过类的函数，取入取出。
如果外部程序不是经常需要使用这个类成员变量的话, 这样get, 对程序的效率影响不大,

**Comment by jihuayu** [comment]
[如何修改issues](https://oop.jihuayu.site/help/issues.html#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9issue)
那把变量开成private，然后通过get，set来存取，有什么好处吗？

**Comment by chinese-Qtea** [comment]
只通过get，set进行操作，可以简单的进行赋值，同时还可以加入其他处理，减少特殊操作，并且类型安全。

**Comment by fzuycy** [comment]
> [如何修改issues](https://oop.jihuayu.site/help/issues.html#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9issue)
> 那把变量开成private，然后通过get，set来存取，有什么好处吗？

能保证安全性吧，就比如如果一个用户输入数据，如果不是用成员函数的形式访问来保证用户输入数据的有效性，而是让用户直接访问数据成员，那很可能会出现用户输入的数据是无效的，然后程序使用这个无效数据会出错。再者，用private能保证一些信息能被封装起来，保护某些信息。

**Comment by jihuayu** [comment]
很好，这个问题差不多了，你们还有什么要补充的吗？

**Comment by fzu-CCchaos** [comment]
类的作用域怎么理解呢？类的作用域和类的成员的访问级别有关系么？没有看懂度娘说的...

**Comment by zhmushan** [comment]
> 类的作用域怎么理解呢？类的作用域和类的成员的访问级别有关系么？没有看懂度娘说的...

@fzu-CCchaos 不仅仅是类，作用域简单的来说，就是你声明的代码有意义的区域，通常情况下，我们可以想当然地认为每一对 `{}` 代表一个作用域，例子（伪代码）：
```cpp
{
  int a = 100
  cout << a // 100
}
cout << a // 出错
```
以类为例：
```cpp
class A {
  int _prop;

 public:
  int prop;
};
```
这段代码，我们在类 `A` 的一对大括号中，可以随意对私有属性 `_prop` 读写，而一旦超出这个范围就不行了，这也就是所谓的封装（你不需要知道他是怎么做的，就算你知道也改不了）
