### ISSUE TITLE
关键词介绍(volatile)

### ISSUE THREAD

**Issue by fzu-CCchaos** [jihuayu/FZU-OOP-2020#2]
本人的一些理解，可能不太准确，希望大佬指正~
-  volatile的本意是“易变的”，它是一个修饰符。
-  用volatile来修饰变量(使用方法例如 volatile int a)可以保证编译器每次用到这个变量的时候都必须到内存处重新读取这个变量的值，不能使用保存在寄存器里的内容。
-  我觉得这样可以提升这个变量的安全性，因为这样不管是寄存器里的内容还是变量本身发生改变，调用的时候都保证使用变量本身，可以保证特殊地址的稳定访问。

**Comment by jihuayu** [comment]
你的回答有这些问题：
1. 标题，标题不明确，你介绍的是什么关键词。
2. 内容不明确，全糊在一起，很难看出来，请分点。

你可以通过点右上角的三个点修改段落。

**Comment by fzu-CCchaos** [comment]
> 
> 
> 本蒟蒻的一些理解，可能不太准确，希望大佬指正~
> 1.volatile的本意是“易变的”，它是一个修饰符。
 2.用volatile来修饰变量(使用方法例如 volatile int a)可以保证编译器每次用到这个变量的时候都必须到内存处重新读取这个变量的值，不能使用保存在寄存器里的内容。
3.我觉得这样可以提升这个变量的安全性，因为这样不管是寄存器里的内容还是变量本身发生改变，调用的时候都保证使用变量本身，可以保证特殊地址的稳定访问。

**Comment by jihuayu** [comment]
![修改标题](https://user-images.githubusercontent.com/32858525/72990602-6b200d80-3e2b-11ea-8d88-084509b6aca6.png)
![修改文本](https://user-images.githubusercontent.com/32858525/72990603-6bb8a400-3e2b-11ea-9c4c-bc19efe8b688.png)
@fzu-CCchaos

**Comment by jihuayu** [comment]
@fzu-CCchaos 帮你修改了内容，请去看一下我是怎么改的，加紧学习markdown语法，加油。
