### ISSUE TITLE
这问题该怎么解决？

### ISSUE THREAD

**Issue by LRlicious** [jihuayu/FZU-OOP-2020#22]
这无法编译该怎么解决，是我vscode还没配置好吗
![bug1](https://user-images.githubusercontent.com/60052937/73137522-04e9f380-4094-11ea-805c-bcba17f1b36c.png)

**Comment by LRlicious** [comment]
发觉好像是命名的问题。。。vscode编译的文件的路径不能有中文吗。。。

**Comment by jihuayu** [comment]
最好不要
