### ISSUE TITLE
#if、if、#ifdef、#if defined之间的区别

### ISSUE THREAD

**Issue by 2002ljy** [jihuayu/FZU-OOP-2020#3]
# #if、if、#ifdef、#if defined之间的区别
[参考网址](https://blog.csdn.net/CLinuxF/article/details/79138770)
下面是这篇文章的部分内容：
## 概念说明
条件编译是C语言中预处理部分的内容，它是编译器编译代码时最先处理的部分。
-  条件编译里面有判断语句：
比如 #if 、#else 、#elif 及 #endif
-  条件编译的意思是：
如果宏条件符合，编译器就编译这段代码，否则，编译器就忽略这段代码而不编译
-  对于if语句：
if 是 C 语言中的关键字，它根据表达式的计算结果来决定执行那个语句，它里面的每个分支是都编译了的
-  如何判断何时使用if何时使用#if：      
如果你的条件在程序编译前就已经确定了，那就用#if。
如果条件需要在程序运行过程中才能判断，则用if。
- 小总结：
简单地讲，条件编译是根据 宏条件 选择性地编译语句，它是编译器在编译代码时完成的；
条件语句是根据条件表达式选择性地执行语句，它是在程序运行时进行的
## 使用说明
- #if的使用说明
if的后面接的是表达式
例如：

```C
#if (MAX==10)||(MAX==20)
...code...
#endif
```

它的作用是：
如果(MAX==10)||(MAX==20)成立，那么编译器就会把其中的#if 与 #endif之间的代码编译进去
（注意：是编译进去，不是执行！！）
-  #if defined的使用：
if后面接的是一个宏。
例如：
```C
#if defined (x)
...code...
#endif
```
这个#if defined它不管里面的“x”的逻辑是“真”还是“假”它只管这个程序的前面的宏定义里面有没有定义“x”这个宏，如果定义了x个宏，那么，编译器会编译中间的…code…否则不直接忽视中间的…code…代码。
另外 #if defined(x)也可以取反，也就用 #if !defined(x)
-  #ifdef的使用：
ifdef的使用和#if defined()的用法一致
ifndef又和#if !defined()的用法一致。
## 强调点：
- 这几个宏定义只是决定代码块是否被编译。
- 别忘了#endif

**Comment by jihuayu** [comment]
请修改一下排版，可以使用preview预览。
如何修改已经发布的issues请查看这个，[地址](https://github.com/jihuayu/FZU-OOP-2020/issues/2#issuecomment-577692692)

**Comment by 2002ljy** [comment]
> 请修改一下排版，可以使用preview预览。
> 如何修改已经发布的issues请查看这个，地址

这样会好一些吗？

**Comment by jihuayu** [comment]
@2002ljy 帮你改好了，自己去看一下我是怎么改的，请加紧学习markdown语法，加油。
