### ISSUE TITLE
c++编译执行过程中的第二步编译

### ISSUE THREAD

**Issue by 83675299** [jihuayu/FZU-OOP-2020#32]
第一步通过预处理命令生成.ii文件，第二步编译生成.s文件，但我操作时为什么不能生成.s文件呢？
如图
![](https://img2018.cnblogs.com/blog/1925125/202001/1925125-20200129155703848-667927172.png)
![](https://img2018.cnblogs.com/blog/1925125/202001/1925125-20200129155739998-1699214309.png)
求解。

**Comment by 83675299** [comment]
为什么没图呢。。。
你们能看见图片吗，我看不见。。。

**Comment by jihuayu** [comment]
你用的是gcc的参数，cl的参数请执行查阅。

**Comment by 83675299** [comment]
好的，谢谢

**Comment by 83675299** [comment]
我找了好久，但找不到cl对c++的详细编译过程，基本都是gcc的，要么就直接生成exe文件，没有生成.s的过程，求助。。。

**Comment by jihuayu** [comment]
[ms官网](https://docs.microsoft.com/zh-cn/cpp/build/reference/compiler-command-line-syntax?view=vs-2019)有自己找。
