### ISSUE TITLE
Markdown基本语法

### ISSUE THREAD

**Issue by 2002ljy** [jihuayu/FZU-OOP-2020#7]
#[markdown基本语法](https://www.cnblogs.com/nickchen121/p/10821946.html)
### 一、标题
<br># 一级标题</br>                                                                
<br>## 二级标题</br>
<br>### 三级标题</br>
<br>#### 四级标题</br>
<br>##### 五级标题</br>
<br>###### 最小只有六级标题
### 二、换行
代码：
`<br>内容</br>`
效果：
如上
### 三、加粗
代码：
`**我被加粗了**`
效果：
**我被加粗了**
### 四、斜体
代码：
`*我倾斜了*`
效果：
*我倾斜了*
### 五、高亮
代码：
`==我高亮了==`
效果：
==我高亮了==
（我没看出什么变化？？？）
### 六、[上标](https://www.jianshu.com/p/80ac23666a98)
代码：
`2<sup>2</sup>`
效果：
2<sup>2</sup>
### 七、[下标](https://www.jianshu.com/p/80ac23666a98)
代码：
`a=log<sub>2</sub>b`
效果：
a=log<sub>2</sub>b
### 八、代码引用（>式）
代码：
`> hello markdown!`
效果：
> hello markdown!

    
多层嵌套式
    代码：
`> hello markdown!`
`>> hello markdown!`
效果：
> hello markdown!
>> hello markdown!

### 九、代码引用（\`\`\`式）
第一行反引号后面，输入代码块所使用的语言
代码：
\`\`\`python
print('hello nick')
\`\`\`

效果：
```python
print('hello nick')
```
### 十、代码引入（\`式）
代码：
\`print('hello nick')\`

    效果：
  `print('hello nick')`
### 十一、插入链接（链接显示）
代码：
`<https://www.cnblogs.com/nickchen121/p/10718112.html>`
效果：
<https://www.cnblogs.com/nickchen121/p/10718112.html>
### 十二、插入链接（链接描述显示）
代码：
`[nickchen博客](https://www.cnblogs.com/nickchen121/p/10718112.html "nickchen博客")`
效果：
[nickchen博客](https://www.cnblogs.com/nickchen121/p/10718112.html "nickchen博客")
#### 1.插入本地图片
只需要在基础语法的括号中填入图片的位置路径即可，支持绝对路径和相对路径。
例如：`![avatar](/home/picture/1.png)`
>不灵活不好分享，本地图片的路径更改或丢失都会造成markdown文件调不出图

#### 2.插入网络图片
只需要在基础语法的括号中填入图片的网络链接即可，现在已经有很多免费/收费图床和方便传图的小工具可选。
例如：
`![avatar](http://baidu.com/pic/doge.png)`
>将图片存在网络服务器上，非常依赖网络。

#### 3.把图片存入markdown文件
* 高级用法
比如：
* `![avatar][base64str]`
* `[base64str]:data:image/png;base64,iVBORw0...`
### 十四、有序列表
代码：
`1. one`
`2. two`
`3. three`
效果：
1. one
2. two 
3. three
### 十五、无序列表
代码：
`* one`
`* two`
`* three`
效果：
* one
* two
* three
注意\*号后要有空格，除了用\*号还可以用+号，-号，用法与*号相同。
### 十六、分割线
代码（以下四种都可以）：
* `***`
* `---`
* `___`
* `- - -`
效果：

***
### 十七、表格
第二行必须得有，并且第二行的冒号代表对齐格式，分别为居中；右对齐；左对齐
代码：
`name | age | sex `
`:-:|:-|-:`
`tony|20|男`
`lucy|18|女`
效果：

name | age | sex 
:-:|:-|-:
tony|20|男
lucy|18|女

以上是我搜索到的常用的Markdown语法，欢迎各位补充。

**Comment by jihuayu** [comment]
这个东西你发一个PR。文章放到doc/draft文件夹里。此处只留下简要介绍并关联该PR。
- [PR](https://oop.jihuayu.site/help/pr.html)
- [推荐博客](https://oop.jihuayu.site/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C.html#%E6%8E%A8%E8%8D%90%E5%8D%9A%E5%AE%A2)

**Comment by 2002ljy** [comment]
> 这个东西你发一个PR。文章放到doc/draft文件夹里。此处只留下简要介绍并关联该PR。
> 
> PR
> 推荐博客

好，我康康这个东西怎么发。</br>这个是我从博客直接复制过来的，不知道为什么预览的标题的\#号是暴露在外的。。

**Comment by zhmushan** [comment]
@2002ljy 关于如何提交 pr 你可以参考 #16 #18 我提交时更改了什么内容。
`#`暴露在外面，你需要在后面添加一个空格

**Comment by 2002ljy** [comment]
> @2002ljy 关于如何提交 pr 你可以参考 #16 #18 我提交时更改了什么内容。
> #暴露在外面，你需要在后面添加一个空格

好的，谢谢！

**Comment by JustinRochester** [comment]
我补充一些内容可以加分吗 ~~doge~~

**Comment by jihuayu** [comment]
可以补充，或者你直接把你修改后的内容发pr到仓库。

**Comment by JustinRochester** [comment]
> 可以补充，或者你直接把你修改后的内容发pr到仓库。

那我先学一下pr

**Comment by 2002ljy** [comment]
> 这个东西你发一个PR。文章放到doc/draft文件夹里。此处只留下简要介绍并关联该PR。
> 
> PR
> 推荐博客

我刚刚点完push origin没有错误提示了，这样算是发到仓库了吗？

**Comment by jihuayu** [comment]
#21
